global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: otel-collector
    static_configs:
      - targets: ['otel-collector:8889']
    metric_relabel_configs:
      - source_labels: [traffic.source]
        regex: ''
        action: replace
        replacement: user
        target_label: traffic.source
      - action: keep
        regex: "otelcol_.*|lokaltreu_.*"
        source_labels: ["__name__"]
