app = "lokaltreu-obs-loki"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[experimental]
  auto_rollback = true

[http_service]
  internal_port = 3100
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 1

[[checks]]
  type = "http"
  name = "http-3100"
  port = 3100
  interval = "15s"
  timeout = "2s"
  method = "GET"
  path = "/ready"

[[mounts]]
  source = "loki_data"
  destination = "/var/loki"
