app = "obs-grafana"
primary_region = "fra"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1

  [[http_service.checks]]
    type = "http"
    interval = "10s"
    timeout = "2s"
    grace_period = "90s"
    method = "GET"
    path = "/api/health"

[env]
  GF_SERVER_HTTP_ADDR = "0.0.0.0"
  GF_SERVER_HTTP_PORT = "3000"
  GF_SERVER_ROOT_URL = "https://obs-grafana.fly.dev"
