app = "lokaltreu-obs-grafana"
primary_region = "fra"

image = "grafana/grafana:10.4.3"

[env]
GF_SECURITY_ADMIN_USER = "admin"
GF_SECURITY_ADMIN_PASSWORD = "admin"   # nur Dev
GF_SERVER_HTTP_ADDR = "0.0.0.0"
GF_SERVER_HTTP_PORT = "3000"

[http_service]
internal_port = 3000
force_https = true
auto_start_machines = false
auto_stop_machines = true
min_machines_running = 0
