app = "lokaltreu-api"
primary_region = "fra"

[env]
OTEL_EXPORTER_OTLP_ENDPOINT = "https://lokaltreu-obs-tempo.fly.dev:4318"
OTEL_EXPORTER_OTLP_PROTOCOL = "http/protobuf"
OTEL_TRACES_EXPORTER = "otlp"
OTEL_METRICS_EXPORTER = "otlp"
OTEL_LOGS_EXPORTER = "otlp"
OTEL_EXPORTER_OTLP_HEADERS = "Authorization=Bearer ${OTEL_BEARER_TOKEN}"
OTEL_RESOURCE_ATTRIBUTES = "service.name=lokaltreu-api,deployment.environment=prod"


